FROM httpd
COPY ./web/ /usr/local/apache2/htdocs/
EXPOSE 80

# docker build -t web_apache . # build here (.) with -t web_apache
# docker run -d -p 80:80 # run detached and on port 80 (local) mapped to 80 (on docker)